Handling cancel image upload 373
BCStudentSoftwareDevTeam/cas pull request #396
Opened 2021-06-07 16:35 UTC by zachneill

Cancelling or removing image removes the image from the peewee database and deletes the file from the folder. Fixes the issue where you have to click remove, refresh the page, then click remove again for the file to be removed. Also actually deletes the file, whereas it would previously just be hidden. Cancelling also works. 

Added multipart/form-data to buildingManagement.html
Used same JS function method for either removing or cancelling. 
Added os remove function to delete the file. 
Resets roomImageURL to null.

How to test: 
Upload an image and remove it, You may refresh the page and check the database and file directory. 
Or, upload a large file and cancel it before it uploads completely.

2021-06-07 21:02 UTC, zachneill commented
![](https://github.trello.services/images/mini-trello-icon.png) [CAS #373: Cancelling an image upload in building management is not handled](https://trello.com/c/RiX7rsoJ/233-cas-373-cancelling-an-image-upload-in-building-management-is-not-handled)

2021-09-14 15:41 UTC, bryantal commented on app/controllers/main_routes/buildingManagement.py
> +    # except Exception as e:
Are these supposed to be commented out?

2022-02-07 19:49 UTC, BrianRamsay commented
@zachneill , there's a comment from Alex not addressed. Can you get this one squared away?

2022-02-15 19:50 UTC, bryantal requested changes
Hmm I don't think we want that image in development

2022-02-16 21:46 UTC, bryantal approved these changes

2022-02-24 16:27 UTC, BrianRamsay approved these changes

2022-02-24 16:27 UTC, merged